/**
 * Installation Event Handler
 *
 * Handles GitHub App installation webhooks:
 *   - installation.created: App installed on account, scaffold CODEOWNERS for each repo
 *   - installation_repositories.added: Repos added to existing installation
 *
 * For each new repository, checks whether a CODEOWNERS file already exists.
 * If one does not exist, the handler creates a branch and opens a PR with a
 * default template so the repository owner can review and customise it before
 * merging.
 */

import type { Octokit } from "@octokit/rest";
import { getInstallationOctokit } from "../utils/auth.js";

// ─── Types ────────────────────────────────────────────────────────────────────

interface Repository {
  name: string;
  full_name: string;
  private: boolean;
}

export interface InstallationPayload {
  action: string;
  installation: {
    id: number;
    account: { login: string };
  };
  /** Populated for `installation` events with action `created`. */
  repositories?: Repository[];
  /** Populated for `installation_repositories` events with action `added`. */
  repositories_added?: Repository[];
  sender: { login: string };
}

export interface ScaffoldResult {
  repository: string;
  skipped: boolean;
  pr_url?: string;
  message: string;
}

/**
 * Injectable scaffolding function signature.
 * Matches {@link scaffoldCodeowners} so tests can provide a mock.
 */
export type ScaffoldFn = (
  owner: string,
  repo: string,
  installationId: number,
  octokit?: Octokit,
) => Promise<ScaffoldResult>;

// ─── Constants ────────────────────────────────────────────────────────────────

const SETUP_BRANCH = "agentcraftworks/setup-codeowners";
const CODEOWNERS_PATH = ".github/CODEOWNERS";

/** All valid CODEOWNERS locations that GitHub recognises. */
const CODEOWNERS_LOCATIONS = [
  ".github/CODEOWNERS",
  "CODEOWNERS",
  "docs/CODEOWNERS",
];

// ─── Default Template ─────────────────────────────────────────────────────────

export const DEFAULT_CODEOWNERS_TEMPLATE = `# CODEOWNERS — Generated by AgentCraftworks
#
# This default template routes files to agent + human reviewers.
# Customize the paths and teams below to match your project.

# Security-critical code → security scanner agent + human lead
*.js              @agents/security-scanner @human-leads/security
*.ts              @agents/security-scanner @human-leads/security
package.json      @agents/security-scanner @human-leads/security
package-lock.json @agents/security-scanner @human-leads/security

# Documentation → docs reviewer agent (autonomous)
docs/**           @agents/docs-reviewer
*.md              @agents/docs-reviewer
README.md         @agents/docs-reviewer @human-leads/docs

# Infrastructure → humans-only (no agent writes without oversight)
.github/**        @human-leads/platform
infra/**          @human-leads/platform
Dockerfile        @human-leads/platform

# Catch-all → code reviewer agent + team leads
*                 @agents/code-reviewer @human-leads/team
`;

const PR_TITLE = "🤖 AgentCraftworks: Add default CODEOWNERS routing";

const PR_BODY = `## 🤖 AgentCraftworks: Default CODEOWNERS Setup

This PR was automatically created by [AgentCraftworks](https://github.com/AgentCraftworks/AgentCraftworks-CE) to scaffold a default \`.github/CODEOWNERS\` file for your repository.

### What is CODEOWNERS?

The \`CODEOWNERS\` file is the **routing layer** for AgentCraftworks. It determines which agents and human reviewers are notified when specific files change in a pull request.

### Default routing in this PR

| Pattern | Reviewers | Reason |
|---------|-----------|--------|
| \`*.js\`, \`*.ts\` | \`@agents/security-scanner\` + \`@human-leads/security\` | Security-critical code changes |
| \`package.json\`, \`package-lock.json\` | \`@agents/security-scanner\` + \`@human-leads/security\` | Dependency security |
| \`docs/**\`, \`*.md\` | \`@agents/docs-reviewer\` | Documentation review |
| \`README.md\` | \`@agents/docs-reviewer\` + \`@human-leads/docs\` | Primary docs with human oversight |
| \`.github/**\`, \`infra/**\`, \`Dockerfile\` | \`@human-leads/platform\` | Infrastructure — humans only |
| \`*\` (catch-all) | \`@agents/code-reviewer\` + \`@human-leads/team\` | All other files |

### Next steps

1. **Review** the patterns above and customise them for your project structure
2. **Replace** team handles (e.g. \`@human-leads/security\`) with your actual GitHub teams
3. **Add** language-specific patterns if your project uses Python, Go, Rust, etc.
4. **Merge** this PR to activate agent routing

> ℹ️ If you already have a CODEOWNERS file elsewhere, you can close this PR.

---
*Generated by AgentCraftworks CE — [Documentation](https://github.com/AgentCraftworks/AgentCraftworks-CE)*`;

// ─── Core Logic ───────────────────────────────────────────────────────────────

/**
 * Check whether any CODEOWNERS file already exists in the repository.
 * Checks all three locations that GitHub recognises:
 *   `.github/CODEOWNERS`, `CODEOWNERS`, and `docs/CODEOWNERS`.
 */
export async function codeownersExists(
  octokit: Octokit,
  owner: string,
  repo: string,
): Promise<boolean> {
  for (const path of CODEOWNERS_LOCATIONS) {
    try {
      await octokit.request("GET /repos/{owner}/{repo}/contents/{path}", {
        owner,
        repo,
        path,
      });
      return true;
    } catch (err: unknown) {
      if (isNotFoundError(err)) continue;
      throw err;
    }
  }
  return false;
}

/**
 * Scaffold a default `.github/CODEOWNERS` file in a repository.
 *
 * - Creates a branch `agentcraftworks/setup-codeowners` from the default branch.
 * - Commits the default CODEOWNERS template to that branch.
 * - Opens a PR against the default branch.
 *
 * Returns a {@link ScaffoldResult} describing what happened.
 * If `octokit` is omitted, an authenticated client is obtained automatically
 * using the provided `installationId`.
 */
export async function scaffoldCodeowners(
  owner: string,
  repo: string,
  installationId: number,
  octokit?: Octokit,
): Promise<ScaffoldResult> {
  const client = octokit ?? (await getInstallationOctokit(installationId));

  // Skip if a CODEOWNERS file already exists anywhere in the repo.
  const exists = await codeownersExists(client, owner, repo);
  if (exists) {
    return {
      repository: `${owner}/${repo}`,
      skipped: true,
      message: "CODEOWNERS already exists — skipped",
    };
  }

  // Resolve the default branch and its current HEAD SHA.
  const repoData = await client.request("GET /repos/{owner}/{repo}", {
    owner,
    repo,
  });
  const defaultBranch = (repoData.data as { default_branch: string })
    .default_branch;

  const refData = await client.request(
    "GET /repos/{owner}/{repo}/git/ref/{ref}",
    {
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    },
  );
  const baseSha = (refData.data as { object: { sha: string } }).object.sha;

  // Create the setup branch (update in place if it already exists so the
  // handler is idempotent on retries).
  try {
    await client.request("POST /repos/{owner}/{repo}/git/refs", {
      owner,
      repo,
      ref: `refs/heads/${SETUP_BRANCH}`,
      sha: baseSha,
    });
  } catch (err: unknown) {
    if (isUnprocessableEntityError(err)) {
      // Branch exists from a previous attempt — force-update to base SHA.
      await client.request("PATCH /repos/{owner}/{repo}/git/refs/{ref}", {
        owner,
        repo,
        ref: `heads/${SETUP_BRANCH}`,
        sha: baseSha,
        force: true,
      });
    } else {
      throw err;
    }
  }

  // Commit the CODEOWNERS template to the setup branch.
  const encodedContent = Buffer.from(DEFAULT_CODEOWNERS_TEMPLATE).toString(
    "base64",
  );
  await client.request("PUT /repos/{owner}/{repo}/contents/{path}", {
    owner,
    repo,
    path: CODEOWNERS_PATH,
    message: "chore: add default CODEOWNERS routing [AgentCraftworks]",
    content: encodedContent,
    branch: SETUP_BRANCH,
  });

  // Open a PR against the default branch.
  let prUrl: string;
  try {
    const prData = await client.request("POST /repos/{owner}/{repo}/pulls", {
      owner,
      repo,
      title: PR_TITLE,
      body: PR_BODY,
      head: SETUP_BRANCH,
      base: defaultBranch,
    });
    prUrl = (prData.data as { html_url: string }).html_url;
  } catch (err: unknown) {
    if (isUnprocessableEntityError(err)) {
      // A PR from the setup branch to the default branch already exists.
      // Look up the existing open PR so retries remain idempotent.
      const existingPrs = await client.request(
        "GET /repos/{owner}/{repo}/pulls",
        {
          owner,
          repo,
          head: `${owner}:${SETUP_BRANCH}`,
          state: "open",
        },
      );
      const firstPr = (existingPrs.data as { html_url: string }[])[0];
      if (!firstPr) {
        // No matching open PR found; rethrow so the caller can handle.
        throw err;
      }
      prUrl = firstPr.html_url;
    } else {
      throw err;
    }
  }
  return {
    repository: `${owner}/${repo}`,
    skipped: false,
    pr_url: prUrl,
    message: `CODEOWNERS PR created: ${prUrl}`,
  };
}

/**
 * Handle an `installation` or `installation_repositories` webhook event.
 *
 * Extracts the list of affected repositories and calls
 * {@link scaffoldCodeowners} for each one.  Errors for individual
 * repositories are captured and surfaced in the result list rather than
 * propagated, so a failure for one repo does not block others.
 *
 * @param scaffoldFn - Optional override for the scaffolding implementation.
 *   Defaults to {@link scaffoldCodeowners}.  Pass a custom function in tests
 *   to avoid real GitHub API calls.
 */
export async function handleInstallationEvent(
  payload: InstallationPayload,
  scaffoldFn: ScaffoldFn = scaffoldCodeowners,
): Promise<{
  handled: boolean;
  action: string;
  results: ScaffoldResult[];
  message: string;
}> {
  const { action, installation } = payload;

  // Determine which repositories to process based on the action.
  let repos: Repository[] = [];
  if (action === "created" && payload.repositories) {
    repos = payload.repositories;
  } else if (action === "added" && payload.repositories_added) {
    repos = payload.repositories_added;
  } else {
    return {
      handled: false,
      action,
      results: [],
      message: `Installation action '${action}' not handled`,
    };
  }

  if (repos.length === 0) {
    return {
      handled: true,
      action,
      results: [],
      message: "No repositories to process",
    };
  }

  const results: ScaffoldResult[] = [];

  // Helper to scaffold CODEOWNERS for a single repository and return a result.
  async function scaffoldRepoForInstallation(
    repo: Repository,
    installationId: number,
  ): Promise<ScaffoldResult> {
    const parts = repo.full_name.split("/");
    if (parts.length !== 2 || !parts[0] || !parts[1]) {
      return {
        repository: repo.full_name,
        skipped: false,
        message: `Error scaffolding CODEOWNERS: malformed repository name '${repo.full_name}'`,
      };
    }

    const owner = parts[0];
    const repoName = parts[1];

    try {
      const result = await scaffoldFn(
        owner,
        repoName,
        installationId,
      );
      return result;
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        repository: repo.full_name,
        skipped: false,
        message: `Error scaffolding CODEOWNERS: ${message}`,
      };
    }
  }

  // Process repositories with a bounded concurrency limit to avoid webhook timeouts
  // while still parallelising work across multiple repositories.
  const CONCURRENCY_LIMIT = 5;
  const queue: Repository[] = [...repos];
  const workerCount = Math.min(CONCURRENCY_LIMIT, queue.length);
  const workers: Promise<void>[] = [];

  for (let i = 0; i < workerCount; i += 1) {
    workers.push(
      (async () => {
        // Each worker pulls repositories from the shared queue until it is empty.
        // Array.prototype.shift is safe here because JavaScript runs this code on a
        // single event loop thread; concurrent access is serialized.
        while (true) {
          const nextRepo = queue.shift();
          if (!nextRepo) {
            return;
          }

          const result = await scaffoldRepoForInstallation(
            nextRepo,
            installation.id,
          );
          results.push(result);
        }
      })(),
    );
  }

  await Promise.all(workers);
  return {
    handled: true,
    action,
    results,
    message: `Processed ${repos.length} repositor${repos.length === 1 ? "y" : "ies"}`,
  };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function isNotFoundError(err: unknown): boolean {
  return (
    typeof err === "object" &&
    err !== null &&
    "status" in err &&
    (err as { status: number }).status === 404
  );
}

function isUnprocessableEntityError(err: unknown): boolean {
  return (
    typeof err === "object" &&
    err !== null &&
    "status" in err &&
    (err as { status: number }).status === 422
  );
}
