/**
 * CLI Consistency Checker — Validates interface consistency across the project.
 *
 * Checks that API route paths, MCP tool names, and job script names follow
 * consistent naming conventions (kebab-case for routes, snake_case for MCP tools).
 * Posts findings as a PR comment or prints to stdout.
 *
 * Environment variables:
 *   GITHUB_TOKEN  — GitHub token for API access
 *   PR_NUMBER     — Optional PR number to comment on
 *   REPOSITORY    — owner/repo string
 *
 * Engagement Level: T2 (Advisor) — posts PR comments with findings, no code edits.
 */

import { Octokit } from "@octokit/rest";
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";

interface ConsistencyIssue {
  file: string;
  line: number;
  issue: string;
  suggestion: string;
}

async function checkRouteConsistency(handlersDir: string): Promise<ConsistencyIssue[]> {
  const issues: ConsistencyIssue[] = [];

  let files;
  try {
    files = await readdir(handlersDir);
  } catch {
    return issues;
  }

  for (const file of files) {
    if (!file.endsWith(".ts")) continue;

    const content = await readFile(join(handlersDir, file), "utf-8");
    const lines = content.split("\n");

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]!;

      // Check route paths use kebab-case
      const routeMatch = line.match(/\.(get|post|put|delete|patch)\s*\(\s*["']([^"']+)["']/);
      if (routeMatch) {
        const path = routeMatch[2]!;
        const segments = path.split("/").filter((s) => s && !s.startsWith(":"));
        for (const segment of segments) {
          if (segment !== segment.toLowerCase()) {
            issues.push({
              file: `handlers/${file}`,
              line: i + 1,
              issue: `Route segment "${segment}" is not lowercase`,
              suggestion: `Use "${segment.toLowerCase()}" instead`,
            });
          }
          if (segment.includes("_") && !segment.startsWith("_")) {
            issues.push({
              file: `handlers/${file}`,
              line: i + 1,
              issue: `Route segment "${segment}" uses underscores`,
              suggestion: `Use kebab-case: "${segment.replace(/_/g, "-")}"`,
            });
          }
        }
      }
    }
  }

  return issues;
}

async function checkMcpConsistency(mcpDir: string): Promise<ConsistencyIssue[]> {
  const issues: ConsistencyIssue[] = [];

  let files;
  try {
    files = await readdir(mcpDir);
  } catch {
    return issues;
  }

  for (const file of files) {
    if (!file.endsWith(".ts")) continue;

    const content = await readFile(join(mcpDir, file), "utf-8");
    const lines = content.split("\n");

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]!;

      // Check MCP tool names use snake_case
      const nameMatch = line.match(/name:\s*["']([^"']+)["']/);
      if (nameMatch) {
        const name = nameMatch[1]!;
        if (name !== name.toLowerCase()) {
          issues.push({
            file: `mcp/${file}`,
            line: i + 1,
            issue: `MCP tool name "${name}" contains uppercase`,
            suggestion: `Use "${name.toLowerCase()}"`,
          });
        }
        if (name.includes("-")) {
          issues.push({
            file: `mcp/${file}`,
            line: i + 1,
            issue: `MCP tool name "${name}" uses kebab-case`,
            suggestion: `Use snake_case: "${name.replace(/-/g, "_")}"`,
          });
        }
      }
    }
  }

  return issues;
}

async function main(): Promise<void> {
  const token = process.env["GITHUB_TOKEN"];
  const prNumber = process.env["PR_NUMBER"];
  const repository = process.env["REPOSITORY"];

  const srcDir = "src";
  const allIssues: ConsistencyIssue[] = [
    ...await checkRouteConsistency(join(srcDir, "handlers")),
    ...await checkMcpConsistency(join(srcDir, "mcp")),
  ];

  if (allIssues.length === 0) {
    console.log("CLI Consistency: All checks passed!");
    return;
  }

  // Build report
  const lines: string[] = [
    "## 🔍 CLI Consistency Report",
    "",
    `Found **${allIssues.length}** consistency issue(s).`,
    "",
    "| File | Line | Issue | Suggestion |",
    "|------|------|-------|------------|",
  ];

  for (const issue of allIssues) {
    lines.push(`| \`${issue.file}\` | ${issue.line} | ${issue.issue} | ${issue.suggestion} |`);
  }

  lines.push(
    "",
    "---",
    "*Generated by GH-AW CLI Consistency Checker — Engagement Level: T2 (Advisor)*",
  );

  const body = lines.join("\n");

  if (token && prNumber && repository) {
    const [owner, repo] = repository.split("/");
    if (owner && repo) {
      const octokit = new Octokit({ auth: token });
      await octokit.issues.createComment({
        owner,
        repo,
        issue_number: parseInt(prNumber, 10),
        body,
      });
      console.log(`CLI Consistency: Posted ${allIssues.length} findings to PR #${prNumber}`);
    }
  } else {
    console.log(body);
  }
}

main().catch((err: unknown) => {
  console.error("CLI Consistency failed:", err instanceof Error ? err.message : err);
  process.exit(1);
});
