/**
 * Daily Test Improver — Identifies test coverage gaps and suggests new tests.
 *
 * Scans source files for modules without corresponding test files, and opens
 * a GitHub issue with specific test suggestions for uncovered modules.
 *
 * Environment variables:
 *   GITHUB_TOKEN  — GitHub token for API access
 *   REPOSITORY    — owner/repo string
 *   TARGET_DIR    — Directory to analyze (default: typescript/src)
 *
 * Engagement Level: T2 (Advisor) — creates issues with suggestions, no code edits.
 */

import { Octokit } from "@octokit/rest";
import { readdir, stat } from "node:fs/promises";
import { join, basename, dirname, relative } from "node:path";

interface CoverageGap {
  sourceFile: string;
  expectedTestFile: string;
  priority: "high" | "medium" | "low";
  reason: string;
}

const HIGH_PRIORITY_DIRS = ["handlers", "services", "middleware"];
const SKIP_DIRS = ["node_modules", "dist", "types", ".git"];
const SKIP_FILES = ["index.ts"];

async function findSourceFiles(dir: string): Promise<string[]> {
  const results: string[] = [];

  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return results;
  }

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);

    if (entry.isDirectory()) {
      if (!SKIP_DIRS.includes(entry.name)) {
        results.push(...await findSourceFiles(fullPath));
      }
    } else if (
      entry.name.endsWith(".ts") &&
      !entry.name.endsWith(".test.ts") &&
      !entry.name.endsWith(".d.ts") &&
      !SKIP_FILES.includes(entry.name)
    ) {
      results.push(fullPath);
    }
  }

  return results;
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

async function main(): Promise<void> {
  const token = process.env["GITHUB_TOKEN"];
  const repository = process.env["REPOSITORY"];
  const targetDir = process.env["TARGET_DIR"] ?? "typescript/src";

  if (!token || !repository) {
    console.log("Daily Test Improver: Missing required environment variables. Skipping.");
    return;
  }

  const [owner, repo] = repository.split("/");
  if (!owner || !repo) {
    console.error("Daily Test Improver: Invalid REPOSITORY format.");
    process.exit(1);
  }

  const octokit = new Octokit({ auth: token });

  // Find all source files
  const sourceFiles = await findSourceFiles(targetDir);
  console.log(`Daily Test Improver: Found ${sourceFiles.length} source files in ${targetDir}`);

  // Check for corresponding test files
  const gaps: CoverageGap[] = [];

  for (const srcFile of sourceFiles) {
    const name = basename(srcFile, ".ts");
    const dir = dirname(srcFile);
    const relPath = relative(process.cwd(), srcFile);

    // Check common test file locations
    const testLocations = [
      join(dir, `${name}.test.ts`),
      join(dir, "__tests__", `${name}.test.ts`),
      srcFile.replace("/src/", "/test/").replace(".ts", ".test.ts"),
    ];

    const hasTest = await Promise.all(testLocations.map(fileExists));

    if (!hasTest.some(Boolean)) {
      const isHighPriority = HIGH_PRIORITY_DIRS.some((d) => relPath.includes(`/${d}/`) || relPath.includes(`\\${d}\\`));
      gaps.push({
        sourceFile: relPath,
        expectedTestFile: testLocations[2] ?? `test/${name}.test.ts`,
        priority: isHighPriority ? "high" : "medium",
        reason: isHighPriority
          ? "Core module in handlers/services/middleware — high impact"
          : "Source file without corresponding test coverage",
      });
    }
  }

  if (gaps.length === 0) {
    console.log("Daily Test Improver: All source files have test coverage!");
    return;
  }

  // Sort by priority
  gaps.sort((a, b) => {
    const order = { high: 0, medium: 1, low: 2 };
    return order[a.priority] - order[b.priority];
  });

  // Build issue body
  const lines: string[] = [
    "## 🧪 Daily Test Coverage Report",
    "",
    `Found **${gaps.length}** source files without test coverage.`,
    "",
    "### High Priority",
    "",
  ];

  const highGaps = gaps.filter((g) => g.priority === "high");
  const medGaps = gaps.filter((g) => g.priority === "medium");

  if (highGaps.length > 0) {
    for (const g of highGaps) {
      lines.push(`- [ ] \`${g.sourceFile}\` — ${g.reason}`);
    }
  } else {
    lines.push("All high-priority modules have test coverage.");
  }

  if (medGaps.length > 0) {
    lines.push("", "### Medium Priority", "");
    for (const g of medGaps.slice(0, 15)) {
      lines.push(`- [ ] \`${g.sourceFile}\``);
    }
    if (medGaps.length > 15) {
      lines.push(`- ... and ${medGaps.length - 15} more`);
    }
  }

  lines.push(
    "",
    "---",
    "*Generated by GH-AW Daily Test Improver — Engagement Level: T2 (Advisor)*",
  );

  const body = lines.join("\n");
  const today = new Date().toISOString().split("T")[0];

  await octokit.issues.create({
    owner,
    repo,
    title: `🧪 Test Coverage Gaps — ${today}`,
    body,
    labels: ["testing", "gh-aw"],
  });

  console.log(`Daily Test Improver: Created issue with ${gaps.length} coverage gaps.`);
}

main().catch((err: unknown) => {
  console.error("Daily Test Improver failed:", err instanceof Error ? err.message : err);
  process.exit(1);
});
