/**
 * PR Fix — Auto-suggests fixes for failing PR checks.
 *
 * Analyzes failed check runs on a PR, reads the logs, and posts review comments
 * with specific fix suggestions. Focuses on actionable, file-level feedback.
 *
 * Environment variables:
 *   GITHUB_TOKEN  — GitHub token for API access
 *   PR_NUMBER     — PR number to analyze
 *   CHECK_RUN_ID  — Optional specific check run to analyze
 *   REPOSITORY    — owner/repo string
 *
 * Engagement Level: T2 (Advisor) — posts review comments, no direct edits.
 */

import { Octokit } from "@octokit/rest";

async function main(): Promise<void> {
  const token = process.env["GITHUB_TOKEN"];
  const prNumber = process.env["PR_NUMBER"];
  const repository = process.env["REPOSITORY"];

  if (!token || !prNumber || !repository) {
    console.log("PR Fix: Missing required environment variables. Skipping.");
    return;
  }

  const [owner, repo] = repository.split("/");
  if (!owner || !repo) {
    console.error("PR Fix: Invalid REPOSITORY format. Expected owner/repo.");
    process.exit(1);
  }

  const octokit = new Octokit({ auth: token });
  const prNum = parseInt(prNumber, 10);

  // Get the PR's check runs
  const { data: pr } = await octokit.pulls.get({
    owner,
    repo,
    pull_number: prNum,
  });

  const { data: checkRuns } = await octokit.checks.listForRef({
    owner,
    repo,
    ref: pr.head.sha,
    filter: "latest",
  });

  const failedChecks = checkRuns.check_runs.filter(
    (cr) => cr.conclusion === "failure",
  );

  if (failedChecks.length === 0) {
    console.log(`PR Fix: No failed checks on PR #${prNum}. Nothing to do.`);
    return;
  }

  // Get changed files in the PR
  const { data: files } = await octokit.pulls.listFiles({
    owner,
    repo,
    pull_number: prNum,
  });

  const changedFiles = files.map((f) => f.filename);

  // Build the review comment
  const lines: string[] = [
    "## 🔧 PR Fix Suggestions",
    "",
    `Found **${failedChecks.length}** failed check(s) on this PR.`,
    "",
  ];

  for (const check of failedChecks) {
    lines.push(`### ❌ ${check.name}`);
    lines.push("");

    if (check.output?.summary) {
      lines.push(check.output.summary);
    } else {
      lines.push(`Check [${check.name}](${check.html_url ?? ""}) failed. Review the logs for details.`);
    }

    // Suggest looking at specific changed files
    const relevantFiles = changedFiles.filter((f) => {
      if (check.name.toLowerCase().includes("type")) return f.endsWith(".ts") || f.endsWith(".tsx");
      if (check.name.toLowerCase().includes("lint")) return f.endsWith(".ts") || f.endsWith(".js");
      if (check.name.toLowerCase().includes("test")) return f.includes("test") || f.includes("spec");
      return true;
    });

    if (relevantFiles.length > 0) {
      lines.push("");
      lines.push("**Files to check:**");
      for (const file of relevantFiles.slice(0, 10)) {
        lines.push(`- \`${file}\``);
      }
    }

    lines.push("");
  }

  lines.push(
    "---",
    "*Generated by GH-AW PR Fix — Engagement Level: T2 (Advisor)*",
  );

  const body = lines.join("\n");

  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: prNum,
    body,
  });

  console.log(`PR Fix: Posted suggestions to PR #${prNum}`);
}

main().catch((err: unknown) => {
  console.error("PR Fix failed:", err instanceof Error ? err.message : err);
  process.exit(1);
});
