name: 🚀 Early Adopter Sign-Up
description: Sign up to beta test AgentCraftworks and help shape agentic DevOps governance.
title: "[Early Adopter] <Your Name / Org>"
labels: ["early-adopter"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 AgentCraftworks Early Adopter Program

        Thanks for your interest! We're looking for **5–10 platform engineering teams** to beta test AgentCraftworks and help shape the future of agentic DevOps governance.

        **What you get:**
        - Free access to AgentCraftworks Community Edition (this repo)
        - 90-day free Enterprise Beta access (invite only)
        - Direct Slack/Discord channel with the founding team
        - Your feedback shapes the product roadmap
        - Early adopter badge + attribution in docs

        Fill out the form below and we'll follow up within **48 hours**.

  - type: input
    id: name_role
    attributes:
      label: Your name / role
      placeholder: "e.g. Jane Smith, Platform Engineer"
    validations:
      required: true

  - type: input
    id: company
    attributes:
      label: Company or org
      description: Can be left anonymous if preferred.
      placeholder: "e.g. Acme Corp (or 'Anonymous')"
    validations:
      required: true

  - type: input
    id: team_size
    attributes:
      label: Team size (approx)
      placeholder: "e.g. 8 engineers"
    validations:
      required: true

  - type: input
    id: cicd_stack
    attributes:
      label: Current CI/CD stack
      placeholder: "e.g. GitHub Actions, Azure DevOps, Jenkins"
    validations:
      required: true

  - type: dropdown
    id: tier
    attributes:
      label: Which tier are you interested in?
      options:
        - CE (free, open source)
        - Enterprise Beta (90-day free trial)
        - Both / Not sure yet
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: One sentence about your use case
      description: What problem would AgentCraftworks solve for you?
      placeholder: "e.g. We want to govern GitHub Copilot agent actions across 20 repos without blocking our teams."
    validations:
      required: true

  - type: checkboxes
    id: acknowledgement
    attributes:
      label: Acknowledgement
      options:
        - label: I'm willing to provide a short written testimonial about my experience after the beta.
          required: false
        - label: I understand my contact information may be used to follow up about the beta program.
          required: true
